nodes:
  - file: data/texts.csv
    label: Text
    properties:
      - 0: ["id", "int"]
      - 1: ["text", "str"]
      - 2: ["publisher", "str"]
  - file: data/annotations.csv
    label: Annotation
    properties:
      - 0: ["id", "int"]
      - 1: [start, int]
      - 2: [stop, int]

edges:
  - file: edges.csv
    properties:
    - 0: [id, int]
    - 1: [id, int]
    - 2: [label, str]

conn:
  - uri: neo4j://localhost:7699
  - database: dhbenelux.db
  - username: neo4j
  - password: password