nodes:
  - file: nodes_person.csv
    label: Person
    properties:
      - id: (id, int)
      - name: (name, str)
      - age: (age, int)
  - file: nodes_city.csv
    label: City
    properties:
      - id: (id, int)
      - name: (name, str)

edges:
  - file: edges_lives_in.csv
    properties:
    - source_node: (id, int)
    - target_node: (id, int)
    - relation: (label, str)

conn: 
  database: abc
  username: abc
  password: abc